#ifndef GSTSIMAAIALLOCATOR_COMMON_H
#define GSTSIMAAIALLOCATOR_COMMON_H

#include <gst/gst.h>
#include <gst/gstallocator.h>
#include <gst/gstmemory.h>

typedef enum
{
  GST_SIMAAI_MEMORY_TARGET_GENERIC = (GST_MEMORY_FLAG_LAST << 0),
  GST_SIMAAI_MEMORY_TARGET_OCM     = (GST_MEMORY_FLAG_LAST << 1),
  GST_SIMAAI_MEMORY_TARGET_DMS0    = (GST_MEMORY_FLAG_LAST << 2),
  GST_SIMAAI_MEMORY_TARGET_DMS1    = (GST_MEMORY_FLAG_LAST << 3),
  GST_SIMAAI_MEMORY_TARGET_DMS2    = (GST_MEMORY_FLAG_LAST << 4),
  GST_SIMAAI_MEMORY_TARGET_DMS3    = (GST_MEMORY_FLAG_LAST << 5),
  GST_SIMAAI_MEMORY_TARGET_EV74    = (GST_MEMORY_FLAG_LAST << 6),
  GST_SIMAAI_MEMORY_FLAG_CACHED    = (GST_MEMORY_FLAG_LAST << 7),
  GST_SIMAAI_MEMORY_FLAG_RDONLY    = (GST_MEMORY_FLAG_LAST << 8),
  GST_SIMAAI_MEMORY_FLAG_DEFAULT   = (GST_MEMORY_FLAG_LAST << 9)
} GstSimaaiMemoryFlags;

#endif